blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('post/<int:post_id>' , views.single, name='single'),
    path('blog/', views.blog, name='blog'),
    path('categorie/<str:cat_name>', views.categorie, name='categorie'),
    path('search/', views.search, name='search'),
    path('contact/', views.contact, name='contact')
]

blogy/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('django/', admin.site.urls),
    path('', include('blog.urls')),
    path('admin/', include('sudo.urls')),
    path('auth/', include('authentication.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Categorie(models.Model):
    name = models.CharField(max_length=50)
    class Meta:
        verbose_name = ("Categorie")
        verbose_name_plural = ("Categories")
    def __str__(self):
        return self.name
    
class Tag(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name
        
    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

class Post(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='media')
    date = models.DateTimeField(auto_now=False, auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    partie1 = models.TextField()
    image1_partie1 = models.ImageField(upload_to='media', blank=True)
    image2_partie1 = models.ImageField(upload_to='media', blank=True)
    image3_partie1 = models.ImageField(upload_to='media', blank=True)
    partie2 = models.TextField(blank=True)
    image1_partie2 = models.ImageField(upload_to='media', blank=True)
    image2_partie2 = models.ImageField(upload_to='media', blank=True)
    image3_partie2 = models.ImageField(upload_to='media', blank=True)
    partie3 = models.TextField(blank=True)
    image1_partie3 = models.ImageField(upload_to='media', blank=True)
    image2_partie3 = models.ImageField(upload_to='media', blank=True)
    image3_partie3 = models.ImageField(upload_to='media', blank=True)
    partie4 = models.TextField(blank=True)
    image1_partie4 = models.ImageField(upload_to='media', blank=True)
    image2_partie4 = models.ImageField(upload_to='media', blank=True)
    image3_partie4 = models.ImageField(upload_to='media', blank=True)
    tags = models.ManyToManyField(Tag, blank=True)
    categorie = models.ForeignKey(Categorie, on_delete=models.CASCADE,  blank=True, null=True)
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'


class Comment(models.Model):

    username = models.CharField(max_length=50)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    email = models.EmailField(max_length=254)
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = ("Comment")
        verbose_name_plural = ("Comments")

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("Comment_detail", kwargs={"pk": self.pk})

class Contact(models.Model):

    username = models.CharField( max_length=50)
    email = models.EmailField(max_length=254, unique=True)
    date = models.DateTimeField(auto_now=False, auto_now_add=True, null=True)

    class Meta:
        verbose_name = ("Contact")
        verbose_name_plural = ("Contacts")

    def __str__(self):
        return self.email

    def get_absolute_url(self):
        return reverse("Contact_detail", kwargs={"pk": self.pk})

class Message(models.Model):

    contact = models.ForeignKey(Contact, on_delete=models.CASCADE)
    subject = models.CharField(max_length=50)
    text = models.TextField()
    date = models.DateTimeField(auto_now=False, auto_now_add=True, null=True)

    class Meta:
        verbose_name = ("Message")
        verbose_name_plural = ("Messages")

    def __str__(self):
        return self.subject

    def get_absolute_url(self):
        return reverse("Message_detail", kwargs={"pk": self.pk})

blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ('username', 'email', 'post', 'message')
        widgets = {
            'username' : forms.TextInput(attrs={
                'class' : 'form-control'
            }),
            'email' : forms.EmailInput(attrs={
                'class' : 'form-control'
            }),
            'message': forms.Textarea(attrs={
                'class' : 'form-control'
            })
        }

blog/views.py
from django.shortcuts import redirect, render
from blog.forms import CommentForm

from blog.models import Categorie, Comment, Post

# Create your views here.

def home(request):
    posts = Post.objects.all().order_by('-date')
    business = Post.objects.filter(categorie = 4).order_by('-date')
    politic = Post.objects.filter(categorie = 6).order_by('-date')
    sante = Post.objects.filter(categorie = 7).order_by('-date')
    travel = Post.objects.filter(categorie = 3).order_by('-date')
    context ={
        'posts' : posts,
        'politic' : politic,
        'bussiness' : business,
        'sante': sante,
        'travel' : travel
    }
    return render(request , 'blog/pages/home.html', context)

def blog(request):
    posts = Post.objects.all()
    context ={
        'posts' : posts
    }
    return render(request, 'blog/pages/blog.html', context)

def single(request, post_id):
    post = Post.objects.get(pk = post_id)
    comments = Comment.objects.filter(post = post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            # Enregistrez le post en base de données
            form.save()
            # Redirigez vers une page de confirmation ou ailleurs
            return redirect('blog')
        else :
            print('invalide form')
    else:
        form = CommentForm()
    context = {
        'post': post,
        'comments' : comments,
        'form' : form
    }
    return render(request, 'blog/pages/single.html', context)

def categorie(request, cat_name):
    print(f'c name : {cat_name}')
    categorie = Categorie.objects.get(name = cat_name)
    print(categorie)
    posts_categorie_name = Post.objects.filter(categorie = categorie)
    print(posts_categorie_name)
    context = {
        'categorie': categorie,
        'posts_categorie_name' : posts_categorie_name
    }
    return render(request , 'blog/pages/categorie.html', context)


def search(request):
    query = request.GET.get('query')
    print(query)
    posts = Post.objects.filter(title__icontains = query)
    context = {
        'query' : query,
        'result_search' : posts
    }
    return render(request, 'blog/pages/search.html', context)

def contact(request):
    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            # Enregistrez le post en base de données
            form.save()
            # Redirigez vers une page de confirmation ou ailleurs
            return redirect('contact')
        else :
            print('invalide form')
    else:
        form = CommentForm()
    context = {
        'form' : form
    }
    return render(request , 'blog/pages/contact.html', context)

blog/templates/blog/pages/blog.html
{% extends "blog/base.html" %}

{% block main %}

  


  <div class="hero overlay inner-page bg-primary py-5">
    <div class="container">
      <div class="row align-items-center justify-content-center text-center pt-5">
        <div class="col-lg-6">
          <h1 class="heading text-white mb-3" data-aos="fade-up">Blog</h1>
        </div>
      </div>
    </div>
  </div>

  <div class="section search-result-wrap">
    <div class="container">
      
      <div class="row posts-entry py-3">
        <div class="col-lg-8 ">
        {% for post  in posts %}
          {% include "blog/includes/post_card_list.html" %}
        {% endfor %}
        
          <div class="row text-start pt-5 border-top">
            <div class="col-md-12">
              <div class="custom-pagination">
                <span>1</span>
                <a href="#">2</a>
                <a href="#">3</a>
                <a href="#">4</a>
                <span>...</span>
                <a href="#">15</a>
              </div>
            </div>
          </div>

        </div>

        {% include "blog/includes/slidebar.html" %}
      </div>
    </div>
  </div>

    <!-- Preloader -->
    <div id="overlayer"></div>
    <div class="loader">
      <div class="spinner-border text-primary" role="status">
        <span class="visually-hidden">Loading...</span>
      </div>
    </div>

    {% endblock main %}

    

blog/templates/blog/pages/categorie.html
{% extends "blog/base.html" %}

{% block main %}

<div class="section search-result-wrap">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="heading">Category: {{ categorie.name }}</div>
            </div>
        </div>
        <div class="row posts-entry">
            <div class="col-lg-8">
                {% for post in posts_categorie_name %}
                <div class="blog-entry d-flex blog-entry-search-item">
                    <a href="{% url "single" post.id %}" class="img-link me-4">
                        <img src="{{ post.image.url }}" alt="Image" class="img-fluid">
                    </a>
                    <div>
                        <span class="date"> {{ post.date }} &bullet; <a href="#">{{post.categorie}}</a></span>
                        <h2><a href="{% url "single" post.id %}">{{ post.title }}</a></h2>
                        <p> {{ post.partie1|truncatewords:15 }} </p>
                        <p><a href="{% url "single" post.id %}" class="btn btn-sm btn-outline-primary">Lire l'article</a></p>
                    </div>
                </div>
                {% endfor %}

                <div class="row text-start pt-5 border-top">
                    <div class="col-md-12">
                        <div class="custom-pagination">
                            <span>1</span>
                            <a href="#">2</a>
                            <a href="#">3</a>
                            <a href="#">4</a>
                            <span>...</span>
                            <a href="#">15</a>
                        </div>
                    </div>
                </div>

            </div>

            {% include "blog/includes/slidebar.html" %}

        </div>
    </div>
</div>

{% endblock main %}

blog/templates/blog/pages/contact.html
{% extends "blog/base.html" %}

{% block main %}
<div class="hero overlay inner-page bg-primary py-5">
    <div class="container">
        <div class="row align-items-center justify-content-center text-center pt-5">
            <div class="col-lg-6">
                <h1 class="heading text-white mb-3" data-aos="fade-up">Contactez nous</h1>
            </div>
        </div>
    </div>
</div>

<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 mb-5 mb-lg-0" data-aos="fade-up" data-aos-delay="100">
                <div class="contact-info">




                    <div class="address mt-2">
                        <i class="icon-room"></i>
                        <h4 class="mb-2">Localisation:</h4>
                        <p>{{blog.localisation}}</p>
                    </div>
                    <div class="email mt-4">
                        <i class="icon-envelope"></i>
                        <h4 class="mb-2">Email:</h4>
                        <p>{{blog.email}}</p>
                    </div>

                    <div class="phone mt-4">
                        <i class="icon-phone"></i>
                        <h4 class="mb-2">telephone:</h4>
                        <p>{{ blog.telephone }}</p>
                    </div>

                </div>
            </div>
            <div class="col-lg-8" data-aos="fade-up" data-aos-delay="200">
                <form action="" method = 'POST'>
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-6 mb-3">
                            {{ form.username }}
                        </div>
                        <div class="col-6 mb-3">
                            {{ form.email }}
                        </div>
                        <div class="col-12 mb-3">
                            <select name="post" required id="id_post">
                                <option value={{ post.id }} selected>---------</option>slot
                            </select>
                            {{ form.post }}
                        </div>
                        <div class="col-12 mb-3">
                            {{ form.message }}
                        </div>

                        <div class="col-12">
                            <input type="submit" value="Envoyer" class="btn btn-primary">
                        </div>
                    </div>
                    
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock main %}

blog/templates/blog/pages/home.html
{% extends "blog/base.html" %}

{% block main %}
<!-- Start retroy layout blog posts -->
	<section class="section bg-light">
		<div class="container">
			<div class="row align-items-stretch retro-layout">
				<div class="col-md-4">
					{% for post in posts|slice:'1:3' %}
				<a href="{% url "single" post.pk %}" class="h-entry mb-3 v-height gradient">
					<div class="featured-img" style="background-image: url('{{ post.image.url }}');"></div>

					<div class="text">
						<span class="date">{{ post.date }}</span>
						<h2>{{ post.title }}</h2>
					</div>
				</a>				
				{% endfor %}
				</div>
				<div class="col-md-4">
					{% for post in posts|slice:':1' %}
					<a href="{% url "single" post.pk %}" class="h-entry mb-3 img-5 h-100 gradient">

						<div class="featured-img" style="background-image: url('{{ post.image.url }}');"></div>

						<div class="text">
							<span class="date">{{ post.date }}</span>
							<h2>{{ post.title }}</h2>
						</div>
					</a>
				{% endfor %}

				</div>
				<div class="col-md-4">
					{% for post in posts|slice:'3:5' %}
					<a href="{% url "single" post.pk %}" class="h-entry mb-3 v-height gradient">
						<div class="featured-img" style="background-image: url('{{ post.image.url }}');"></div>
	
						<div class="text">
							<span class="date">{{ post.date }}</span>
							<h2>{{ post.title }}</h2>
						</div>
					</a>				
					{% endfor %}
				</div>
			</div>
		</div>
	</section>
<!-- End retroy layout blog posts -->

<!-- Start posts-entry -->
<section class="section posts-entry">
	<div class="container">
		<div class="row mb-4">
			<div class="col-sm-6">
				<h2 class="posts-entry-title">Business</h2>
			</div>
			<div class="col-sm-6 text-sm-end"><a href="{% url "categorie" 'business' %}" class="read-more">voir plus</a></div>
		</div>
		<div class="row g-3">
			<div class="col-md-9">
				<div class="row g-3">
					{% for post in bussiness|slice:':2' %}					
					<div class="col-md-6">
						<div class="blog-entry">
							<a href="{% url "single" post.pk %}" class="img-link">
								{% if post.image.url %}
								<img src="{{ post.image.url }}" alt="Image" class="img-fluid">
								{% else %}
								<img src="{{ blog.default_post_image.url }}" alt="Image" class="img-fluid">
								{% endif %}
							</a>
							<span class="date">{{ post.date }}</span>
							<h2><a href="{% url "single" post.pk %}">{{ post.title }}</a></h2>
							<p>{{ post.partie1|truncatewords:20 }}</p>
							<p><a href="{% url "single" post.pk %}" class="btn btn-sm btn-outline-primary">lire l'article</a></p>
						</div>
					</div>
					{% endfor %}
				</div>
			</div>
			<div class="col-md-3">
				<ul class="list-unstyled blog-entry-sm">
					{% for post in bussiness|slice:'2:5' %}					
					<li>
						<span class="date">{{ post.date }}</span>
						<h3><a href="{% url "single" post.pk %}">{{ post.title }}</a></h3>
						<p>{{ post.partie1|truncatewords:20 }}</p>
						<p><a href="{% url "single" post.pk %}" class="read-more">continuer la lecture</a></p>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>
	</div>
</section>
<!-- End posts-entry -->

<!-- Start posts-entry -->
<section class="section posts-entry posts-entry-sm bg-light">
	<div class="container">
		<div class="row">
			{% for post in bussiness|slice:'5:9' %}	
			<div class="col-md-6 col-lg-3">
				<div class="blog-entry">
					<a href="{% url "single" post.pk %}" class="img-link">
						{% if post.image.url %}
								<img src="{{ post.image.url }}" alt="Image" class="img-fluid">
								{% else %}
								<img src="{{ blog.default_post_image.url }}" alt="Image" class="img-fluid">
						{% endif %}
					</a>
					<span class="date">{{ post.date }}</span>
					<h2><a href="{% url "single" post.pk %}">{{ post.title }}</a></h2>
					<p>{{ post.partie1|truncatewords:20 }}</p>
					<p><a href="{% url "single" post.pk %}" class="read-more">continuer la lecture</a></p>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
</section>
<!-- End posts-entry -->

<!-- Start posts-entry -->
<section class="section posts-entry">
	<div class="container">
		<div class="row mb-4">
			<div class="col-sm-6">
				<h2 class="posts-entry-title">Sante</h2>
			</div>
			<div class="col-sm-6 text-sm-end"><a href="{% url "categorie" 'sante' %}" class="read-more">Voir plus</a></div>
		</div>
		<div class="row g-3">
			<div class="col-md-3">
				<ul class="list-unstyled blog-entry-sm">
					{% for post in sante|slice:'2:5' %}					
					<li>
						<span class="date">{{ post.date }}</span>
						<h3><a href="{% url "single" post.pk %}">{{ post.title }}</a></h3>
						<p>{{ post.partie1|truncatewords:20 }}</p>
						<p><a href="{% url "single" post.pk %}" class="read-more">continuer la lecture</a></p>
					</li>
					{% endfor %}
				</ul>
			</div>
			<div class="col-md-9">
				<div class="row g-3">
					{% for post in sante|slice:':2' %}					
					<div class="col-md-6">
						<div class="blog-entry">
							<a href="{% url "single" post.pk %}" class="img-link">
								{% if post.image.url %}
								<img src="{{ post.image.url }}" alt="Image" class="img-fluid">
								{% else %}
								<img src="{{ blog.default_post_image.url }}" alt="Image" class="img-fluid">
								{% endif %}
							</a>
							<span class="date">{{ post.date }}</span>
							<h2><a href="{% url "single" post.pk %}">{{ post.title }}</a></h2>
							<p>{{ post.partie1|truncatewords:20 }}</p>
							<p><a href="{% url "single" post.pk %}" class="btn btn-sm btn-outline-primary">lire l'article</a></p>
						</div>
					</div>
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
</section>

<section class="section">
	<div class="container">

		<div class="row mb-4">
			<div class="col-sm-6">
				<h2 class="posts-entry-title">Politique</h2>
			</div>
			<div class="col-sm-6 text-sm-end"><a href="{% url "categorie" 'politique' %}" class="read-more">View All</a></div>
		</div>

		<div class="row">
			{% for post in politic %}
			<div class="col-lg-4 mb-4">
				<div class="post-entry-alt">
					{% if post.image.url %}
					<a href="single.html" class="img-link"><img src="{{ post.image.url }}" alt="Image" class="img-fluid"></a>
					{% else %}
					<a href="single.html" class="img-link"><img src="{{ blog.default_post_image.url }}" alt="Image" class="img-fluid"></a>
					{% endif %}
					<div class="excerpt">
						

						<h2><a href="single.html">{{ post.title }}</a></h2>
						<div class="post-meta align-items-center text-left clearfix">
							<figure class="author-figure mb-0 me-3 float-start"><img src="{{ blog.default_avatar.url }}" alt="Image" class="img-fluid"></figure>
							<span class="d-inline-block mt-1">By <a href="#">{{ post.author }}</a></span>
							<span>&nbsp;-&nbsp; {{ post.date }}</span>
						</div>

						<p>{{ post.partie1|truncatewords:28 }}</p>
						<p><a href="#" class="read-more">Continue Reading</a></p>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
		
	</div>
</section>

<div class="section bg-light">
	<div class="container">

		<div class="row mb-4">
			<div class="col-sm-6">
				<h2 class="posts-entry-title">Voyage et aventure</h2>
			</div>
			<div class="col-sm-6 text-sm-end"><a href="category.html" class="read-more">View All</a></div>
		</div>

		<div class="row align-items-stretch retro-layout-alt">
			{% for post in sante|slice:':1' %}
			<div class="col-md-5 order-md-2">
				<a href="single.html" class="hentry img-1 h-100 gradient">
					<div class="featured-img" style="background-image: url('{{ post.image.url }}');"></div>
					<div class="text">
						<span>{{ post.date }}</span>
						<h2>{{ post.title }}</h2>
					</div>
				</a>
			</div>
			{% endfor %}
			<div class="col-md-7">
				
				{% for post in sante|slice:'1:2' %}
				<a href="single.html" class="hentry img-2 v-height mb30 gradient">
					<div class="featured-img" style="background-image: url('{{ post.image.url }}');"></div>
					<div class="text text-sm">
						<span>{{ post.date }}</span>
						<h2>{{ post.title }}</h2>
					</div>
				</a>
			{% endfor %}
			<div class="two-col d-block d-md-flex justify-content-between">
					{% for post in sante|slice:'2:4' %}
					<a href="single.html" class="hentry v-height img-2 gradient">
						<div class="featured-img" style="background-image: url('{{ post.image.url }}');"></div>
						<div class="text text-sm">
							<span>{{ post.date }}</span>
							<h2>Don’t assume your user data in the cloud is safe</h2>
						</div>
					</a>
			{% endfor %}
				</div>  
			</div>
		</div>

	</div>
</div>
 <!-- /.site-footer -->
 {% endblock main %}

blog/templates/blog/pages/search.html
{% extends "blog/base.html" %}

{% block main %}

<div class="section search-result-wrap">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="heading">Resultas de recherche pour  : {{ query }}</div>
            </div>
        </div>
        <div class="row posts-entry">
            <div class="col-lg-8">
                {% for post  in result_search %}
                {% include "blog/includes/post_card_list.html" %}
                {% endfor %}
                <div class="row text-start pt-5 border-top">
                    <div class="col-md-12">
                        <div class="custom-pagination">
                            <span>1</span>
                            <a href="#">2</a>
                            <a href="#">3</a>
                            <a href="#">4</a>
                            <span>...</span>
                            <a href="#">15</a>
                        </div>
                    </div>
                </div>

            </div>

            {% include "blog/includes/slidebar.html" %}

        </div>
    </div>
</div>

{% endblock main %}

blog/templates/blog/pages/single.html
{% extends "blog/base.html" %}

{% block main %}
  <div class="site-cover site-cover-sm same-height overlay single-page" style="background-image: url('{{ post.image.url }}');">
    <div class="container">
      <div class="row same-height justify-content-center">
        <div class="col-md-6">
          <div class="post-entry text-center">
            <h1 class="mb-4">{{ post.title }}</h1>
            <div class="post-meta align-items-center text-center">
              <figure class="author-figure mb-0 me-3 d-inline-block">
                {% comment %} <img src="{{ post.image.url }}" alt="Image" class="img-fluid"> {% endcomment %}
            </figure>
            {% if post.author.first_name and post.author.last_name %}
            <span class="d-inline-block mt-1">{{ post.author.first_name }} {{ post.author.last_name }}</span>
            {% else %}
            <span class="d-inline-block mt-1">{{ post.author.username }}</span>
            {% endif %}
              <span>&nbsp;-&nbsp; {{ post.date }}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <section class="section">
    <div class="container">

      <div class="row blog-entries element-animate">

        <div class="col-md-12 col-lg-8 main-content">

          <div class="post-content-body">
            <p>{{ post.partie1 }}</p>
            <div class="row my-4">
              <div class="col-md-12 mb-4">
                <img src="{{ post.image1_partie1.url }}" alt="Image placeholder" class="img-fluid rounded">
              </div>
              <div class="col-md-6 mb-4">
                <img src="{{ post.image2_partie1.url }}" alt="Image placeholder" class="img-fluid rounded">
              </div>
              <div class="col-md-6 mb-4">
                <img src="{{ post.image3_partie1.url }}" alt="Image placeholder" class="img-fluid rounded">
              </div>
            </div>
            <p>{{ post.partie2 }}</p>
            
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus magni explicabo id molestiae, minima quas assumenda consectetur, nobis neque rem, incidunt quam tempore perferendis provident obcaecati sapiente, animi vel expedita omnis quae ipsa! Obcaecati eligendi sed odio labore vero reiciendis facere accusamus molestias eaque impedit, consequuntur quae fuga vitae fugit?</p>
          </div>


          <div class="pt-5">
            <p>Categories:  <a href="#"> {{ post.categorie }}</a>  Tags: <a href="#">
                {% comment %} {% for tag in post.tags %} {% endcomment %}
                <a href="#">{{ post.tags }}</a>
                {% comment %} {% endfor %} {% endcomment %}
            </p>
          </div>


          <div class="pt-5 comment-wrap">
            <h3 class="mb-5 heading">{{ comments|length }} comentaires</h3>
            <ul class="comment-list">
                {% for comment in comments %}
                <li class="comment">
                    {% comment %} <div class="vcard">
                      <img src="images/person_1.jpg" alt="Image placeholder">
                    </div> {% endcomment %}
                    <div class="comment-body">
                      <h3>{{ comment.username }}</h3>
                      <div class="meta">{{ comment.date }}</div>
                      <p>{{ comment.message }} </p>
                      <p><a href="#" class="reply rounded">Reply</a></p>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <!-- END comment-list -->

            <div class="comment-form-wrap pt-5">
              <h3 class="mb-5">Leave a comment</h3>
              <form action="" method = 'POST'  class="p-5 bg-light">
                {% csrf_token %}
                <select name="post" required id="id_post" class= 'd-none'>
                  <option value={{ post.id }} selected></option>slot
              </select>
                <div class="form-group">
                  <label for="name">Name *</label>
                  {{ form.username }}
                </div>
                <div class="form-group">
                  <label for="email">Email *</label>
                  {{ form.email }}
                </div>
                <div class="form-group">
                  <label for="message">Message</label>
                  {{ form.message }}
                </div>
                <div class="form-group">
                  <input type="submit" value="Post Comment" class="btn btn-primary">
                </div>

              </form>
            </div>
          </div>

        </div>
        {% include "blog/includes/slidebar.html" %}
    </div>
  </section>


  <!-- Start posts-entry -->
  <section class="section posts-entry posts-entry-sm bg-light">
    <div class="container">
      <div class="row mb-4">
        <div class="col-12 text-uppercase text-black">Plus d'articles</div>
      </div>
      <div class="row">
        {% for post in random_posts %}
        {% include "blog/includes/post_card_grid.html" %}
        {% endfor %}
      </div>
    </div>
  </section>
{% endblock main %}
 